### ISSUE TITLE
Negative TIMESHIFT does not work as expected

### ISSUE THREAD

**Issue by xiangsm** [vi/timeskew#1]
A nagative TIMESHIFT value is supposed to report an earlier time.  However,  in the following command:

```
$ TIMESHIFT="-86400" TIMESKEW="60 1" LD_PRELOAD=path/to/libtimeskew.so myprog
```

It's expected myprog got a time value of 1 day before current time, but it actually got '2151-07-02 22:19:17'.  It's about 136 years ahead of current system clock time.  Don't know why.

**Comment by vi** [comment]
```
$ TIMESHIFT="-86400" TIMESKEW="60 1" LD_PRELOAD=~/code/timeskew/libtimeskew.so date
Tue May 26 13:23:51 FET 2015
$ date
Wed May 27 13:23:54 FET 2015
```

Does this test work for you? Which architecture do you have, 32-bit or 64-bit? Does positive or zero timeshift work as expected?

I remember using libtimeskew myself like that (much faster time + jump to the past) on Python code and it worked well.

**Comment by xiangsm** [comment]
```
$ uname -a
Linux janms 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-2 (2015-04-13) x86_64 GNU/Linux
$ date
Wed May 27 23:20:53 CST 2015
$ TIMESHIFT="-86400" TIMESKEW="60 1" LD_PRELOAD=./libtimeskew.so date
Sat Jul  3 05:49:14 CST 2151
```

Zero/positive timeshift works fine.
Thanks for quick reply.

**Comment by xiangsm** [comment]
Added a debug line to override.c:  'fprintf(stderr, "TIMESHIFT=%d\n", shift);'
The output confirms that shift value is correct: TIMESHIFT=-86400

And I have checked the code of override.c, can't figure out why negative shift does not work.

**Comment by xiangsm** [comment]
Replaced

```
static long long int shift;
```

with

```
static int shift;
```

Then the problem is gone.  Now negative timeshift works!
