### ISSUE TITLE
TIMESKEW does not apply?

### ISSUE THREAD

**Issue by nmarasoiu** [vi/timeskew#2]
Hi, It does not seem to work for me:
$ TIMESKEW="20 1" LD_PRELOAD=/home/nicu/timeskew/libtimeskew.so bash
$ date
vineri 16 iunie 2017, 16:08:39 +0300
$ date
vineri 16 iunie 2017, 16:08:40 +0300
$ date
vineri 16 iunie 2017, 16:08:41 +0300
$ date
vineri 16 iunie 2017, 16:08:42 +0300

**Comment by vi** [comment]
The counter for the simulated datetime is not global, but per-process. It is initialized every time you start "date".

Use `TIMESHIFT` environment variable to apply offset to the time. Unfortunately, proper multi-process datetime emulation is not supported (but can be done if needed).

**Comment by nmarasoiu** [comment]
Thank you for explanations
